name: toml
version: 0.4.0
author: Justin Andresen <jan.dresen.95@gmail.com>
description: Parser and encoder for TOML v0.4.0 (Tom's Obvious, Minimal Language) configuration files.
homepage: https://github.com/just95/toml.dart
environment:
  sdk: '>=1.9.1 <2.0.0'
dependencies:
  path: '^1.3.4'
  petitparser: '^1.3.3'
  quiver: '^0.21.0'
  yaml: '^2.1.2'
dev_dependencies:
  test: any
