name: toml
version: 0.1.1
author: Justin Andresen <jan.dresen.95@gmail.com>
description: Parser and encoder for TOML v0.3.1 (Tom's Obvious, Minimal Language) configuration files.
homepage: https://github.com/just95/toml.dart
dependencies:
  dart_config: '>=0.5.0 <0.6.0'
  petitparser: '>=1.3.3 <2.0.0'
dev_dependencies:
  browser: any
  unittest: '>=0.11.5 <0.12.0'
